### ISSUE TITLE
Allow users to supply an options object

### ISSUE THREAD

**Issue by devdutchy** [auralia/node-nsapi#1]
Currently, if you want to change a parameter, you have to supply other parameters too, which is very unpractical, see the following code:
```javascript
const { NsApi } = require("nsapi");

const api = new NsApi("useragent", "option-1", "option-2", "option-I-want-to-change");
...
```
This can be simplified by allowing the user to supply an object instead with the options:
```javascript
const { NsApi } = require("nsapi");

const api = new NsApi("useragent", {
  optionToChange: value
});
...
```
Let me know what you think of it, I think it will be more practical and user-friendly to users.

Also I am happy to see this is still maintained.

**Comment by auralia** [comment]
This is a reasonable request -- I'll make this change in the next release.
